server:
  port: 8762
eureka:
  instance:
    hostname: eureka_server_8762
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/