server:
  port: 9527
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    instance-id: zuule_9527
    prefer-ip-address: false

zuul:
  #ignored-services: microservicecloud-dept #隐藏原服务名称id
  #  prefix: /sunth        #前缀名称
#  ignored-services: "*"  #隐藏所有原服务名称id
  routes:
    CUSTOMER.serviceId: CUSTOMER_HYSTRIX #原服务名称id
    CUSTOMER.path: /sunth/**                  #替代名 映射

    provider.serviceId: PROVIDER
    provider.path: /pro


