server:
  port: 8084
spring:
  application:
    name: provider
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id:  provider_hystrix_8084