server:
  port: 8003
spring:
  application:
    name: Customer_Hystrix
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    instance-id: Customer_Hystrix_8003
    prefer-ip-address: true