server:
  port: 3344
spring:
  application:
    name: config_3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunth73/-microservicecloud-config-.git
          username: sunth73
          password: sunsidemima123!!



