server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    instance-id: customer_8001
    prefer-ip-address: true
spring:
  application:
    name: customer